services:
 redis:
    image: redis:latest
    container_name: test_redis
    command: ['redis-server', '--requirepass', 'Admin123']
    ports:
      - '6379:6379'
    volumes:
      - cache:/data/cache
    networks:
      - network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: '200m'


volumes:
  cache:
    driver: local

networks:
  network:
    driver: bridge
